### ISSUE TITLE
Runtime error creating the guest main stack in the host AWS account

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/aws-operator#780]
When aws operator create a guest cluster in a different AWS account, I have seen an issue for the guest main CF stack creating (there was not list in the AWS console). Debugging the aws operator logs I saw

```
panic: runtime error: index out of range

goroutine 36 [running]:
github.com/giantswarm/aws-operator/service/awsconfig/v4/resource/cloudformation/adapter.routeTableID(0xc42073eb50, 0xf, 0x0, 0x0, 0x0, 0x0, 0xc42073ea38, 0x5, 0x0, 0x0, ...)
	/go/src/github.com/giantswarm/aws-operator/service/awsconfig/v4/resource/cloudformation/adapter/host_route_tables.go:129 +0x4d4
github.com/giantswarm/aws-operator/service/awsconfig/v4/resource/cloudformation/adapter.(*hostRouteTablesAdapter).getHostRouteTables(0xc42024a8e0, 0x0, 0x0, 0x0, 0x0, 0xc42073ea38, 0x5, 0x0, 0x0, 0xc42073ea60, ...)
	/go/src/github.com/giantswarm/aws-operator/service/awsconfig/v4/resource/cloudformation/adapter/host_route_tables.go:39 +0x130
github.com/giantswarm/aws-operator/service/awsconfig/v4/resource/cloudformation/adapter.(*hostRouteTablesAdapter).(github.com/giantswarm/aws-operator/service/awsconfig/v4/resource/cloudformation/adapter.getHostRouteTables)-fm(0x0, 0x0, 0x0, 0x0, 0xc42073ea38, 0x5, 0x0, 0x0, 0xc42073ea60, 0x7, ...)
	/go/src/github.com/giantswarm/aws-operator/service/awsconfig/v4/resource/cloudformation/adapter/adapter.go:126 +0x50
github.com/giantswarm/aws-operator/service/awsconfig/v4/resource/cloudformation/adapter.NewHostPost(0x0, 0x0, 0x0, 0x0, 0xc42073ea38, 0x5, 0x0, 0x0, 0xc42073ea60, 0x7, ...)
	/go/src/github.com/giantswarm/aws-operator/service/awsconfig/v4/resource/cloudformation/adapter/adapter.go:130 +0xfc
github.com/giantswarm/aws-operator/service/awsconfig/v4/resource/cloudformation.(*Resource).getMainHostPostTemplateBody(0xc42048a450, 0x0, 0x0, 0x0, 0x0, 0xc42073ea38, 0x5, 0x0, 0x0, 0xc42073ea60, ...)
	/go/src/github.com/giantswarm/aws-operator/service/awsconfig/v4/resource/cloudformation/main_stack.go:107 +0xe1
github.com/giantswarm/aws-operator/service/awsconfig/v4/resource/cloudformation.(*Resource).createHostPostStack(0xc42048a450, 0x2c2aa60, 0xc420b5cb40, 0x0, 0x0, 0x0, 0x0, 0xc42073ea38, 0x5, 0x0, ...)
```

**Comment by pipo02mix** [comment]
It is was an error with the route table pre-settings in the testing installation. It has been solved.
